#!/usr/bin/env bash
# aws-advisor setup (member account: the child's read role, trusting the parent), generated by http://localhost:9034 on 2026-10-04.
#
# Runs the README's onboarding end to end with the admin credentials of THIS terminal (the advisor never gets
# them): it only ever receives the profile name / role ARN through its API. Every step checks what exists and
# skips or updates it, so rerunning is safe.
#
# What it does:
#   1. Detect the AWS account and the admin identity
#   2. Create the read-only role aws-advisor-read trusted by parent's identity arn:aws:iam::888722792401:role/aws-advisor-read
#   3. Put the read-only policy on aws-advisor-read
#   4. Create the read-only SSM probe documents (AwsAdvisorProbe-host, AwsAdvisorProbe-docker, AwsAdvisorProbe-apps, AwsAdvisorProbe-software) in us-east-1
#   5. Register this account with the advisor (http://localhost:9034) as a member and test the role from the parent
#
# Options: --dry-run (print the commands, change nothing), --api-token TOKEN (or ADVISOR_API_TOKEN in the
# environment: the advisor's API_TOKEN or a token minted by it, when the API is protected), --advisor-url URL.
# Needs: aws (v2), curl; python3 for the trust-policy merge and readable summaries (optional otherwise).
set -euo pipefail

PATH_KIND='member-role'
USER_NAME='aws-advisor'
ROLE_NAME='aws-advisor-read'
PROFILE_NAME='aws-advisor'
SOURCE_PROFILE='aws-advisor-user'
REGION='us-east-1'
INSTANCE_ROLE_NAME='aws-advisor-host'
INSTANCE_ID=''
INSTANCE_LABEL='the EC2 host'
ADVISOR_URL='http://localhost:9034'
ADMIN_PROFILE=''
PROBE_DOCUMENT='AwsAdvisorProbe'
PROBE_VERSION='aws-advisor/2.0'
ASSUME_POLICY_NAME='aws-advisor-assume'
PRINCIPAL_ARN='arn:aws:iam::888722792401:role/aws-advisor-read'
ASSUME_TARGET='arn:aws:iam::<ACCOUNT_ID>:role/aws-advisor-read'
PRINCIPAL_SID='AdvisorParent'
MEMBER_NAME='745666712914'
SSM_CORE_POLICY='arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
TOTAL_STEPS=5
DRY_RUN=0
API_TOKEN="${ADVISOR_API_TOKEN:-}"
ADVISOR_OK=0
ACCOUNT_ID=""
CALLER_ARN=""
ROLE_ARN=""

usage() {
  sed -n '2,/^set -euo/p' "$0" | grep '^#' | sed 's/^# \{0,1\}//'
}
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --api-token) shift; API_TOKEN="${1:-}" ;;
    --api-token=*) API_TOKEN="${1#--api-token=}" ;;
    --advisor-url) shift; ADVISOR_URL="${1:-}" ;;
    --advisor-url=*) ADVISOR_URL="${1#--advisor-url=}" ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done
ADVISOR_URL="${ADVISOR_URL%/}"
TOKEN_HINT=""
[ -z "$API_TOKEN" ] || TOKEN_HINT="-H 'x-api-token: ***' "

tmpbase="${TMPDIR:-/tmp}"
WORK=$(mktemp -d "${tmpbase%/}/aws-advisor-setup.XXXXXX")
cleanup() { [ "$DRY_RUN" = 1 ] || rm -rf "$WORK"; }
trap cleanup EXIT

# The advisor's recommended read-only policy (GET /api/permissions -> recommended_policy); <ACCOUNT_ID> is filled in at run time.
POLICY_JSON=$(cat <<'JSON'
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AdvisorReadOnly",
      "Effect": "Allow",
      "Action": [
        "ec2:Describe*",
        "rds:Describe*",
        "rds:ListTagsForResource",
        "rds:DownloadDBLogFilePortion",
        "pi:DescribeDimensionKeys",
        "pi:GetResourceMetadata",
        "elasticache:Describe*",
        "elasticache:ListTagsForResource",
        "cloudwatch:GetMetricStatistics",
        "cloudwatch:GetMetricData",
        "cloudwatch:ListMetrics",
        "logs:DescribeLogGroups",
        "logs:DescribeLogStreams",
        "logs:ListTagsForResource",
        "logs:DescribeQueries",
        "logs:DescribeSubscriptionFilters",
        "logs:DescribeExportTasks",
        "logs:StartQuery",
        "logs:GetQueryResults",
        "logs:StopQuery",
        "cloudwatch:DescribeAlarms",
        "cloudwatch:ListTagsForResource",
        "kms:ListKeys",
        "kms:DescribeKey",
        "kms:ListAliases",
        "kms:ListResourceTags",
        "kms:GetKeyRotationStatus",
        "elasticfilesystem:DescribeFileSystems",
        "elasticfilesystem:DescribeLifecycleConfiguration",
        "elasticfilesystem:DescribeTags",
        "ce:GetCostAndUsage",
        "ce:GetCostAndUsageWithResources",
        "ce:GetSavingsPlansUtilization",
        "ce:GetSavingsPlansCoverage",
        "ce:GetReservationUtilization",
        "savingsplans:DescribeSavingsPlans",
        "pricing:GetProducts",
        "support:DescribeSeverityLevels",
        "ssm:DescribeInstanceInformation",
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation",
        "s3:GetLifecycleConfiguration",
        "s3:GetBucketTagging",
        "s3:GetBucketVersioning",
        "s3:GetBucketPolicyStatus",
        "s3:ListBucket",
        "s3:ListBucketVersions",
        "s3:ListBucketMultipartUploads",
        "s3:GetMetricsConfiguration",
        "lambda:ListFunctions",
        "lambda:GetFunction*",
        "lambda:GetPolicy",
        "lambda:ListTags",
        "ecr:DescribeRepositories",
        "ecr:DescribeImages",
        "ecr:ListImages",
        "ecr:GetLifecyclePolicy",
        "ecr:ListTagsForResource",
        "ecs:Describe*",
        "ecs:List*",
        "eks:Describe*",
        "eks:List*",
        "dynamodb:Describe*",
        "dynamodb:List*",
        "application-autoscaling:DescribeScalableTargets",
        "elasticloadbalancing:Describe*",
        "secretsmanager:ListSecrets",
        "secretsmanager:DescribeSecret",
        "cloudtrail:DescribeTrails",
        "cloudtrail:GetTrailStatus",
        "cloudtrail:ListTags",
        "cloudtrail:LookupEvents",
        "cloudfront:List*",
        "cloudfront:Get*",
        "route53:List*",
        "route53:Get*",
        "elasticbeanstalk:DescribeEnvironments",
        "elasticbeanstalk:DescribeConfigurationSettings",
        "elasticbeanstalk:DescribeEnvironmentResources",
        "elasticbeanstalk:ListTagsForResource",
        "elasticbeanstalk:DescribeApplicationVersions",
        "autoscaling:Describe*",
        "redshift:Describe*",
        "elasticmapreduce:List*",
        "elasticmapreduce:Describe*",
        "apigateway:GET",
        "tag:GetResources",
        "sts:GetCallerIdentity",
        "iam:ListAccountAliases",
        "iam:SimulatePrincipalPolicy",
        "iam:ListUsers",
        "iam:GetUser",
        "iam:ListAccessKeys",
        "iam:GetAccessKeyLastUsed",
        "iam:ListGroupsForUser",
        "iam:ListAttachedUserPolicies",
        "iam:ListUserPolicies",
        "iam:GetUserPolicy",
        "iam:GetLoginProfile",
        "iam:ListMFADevices",
        "iam:ListUserTags",
        "organizations:DescribeOrganization",
        "organizations:ListAccounts"
      ],
      "Resource": "*"
    },
    {
      "Sid": "AdvisorAssumeMembers",
      "Effect": "Allow",
      "Action": [
        "sts:AssumeRole"
      ],
      "Resource": [
        "arn:aws:iam::*:role/aws-advisor-read"
      ]
    },
    {
      "Sid": "AdvisorSsmProbe",
      "Effect": "Allow",
      "Action": [
        "ssm:SendCommand"
      ],
      "Resource": [
        "arn:aws:ssm:*:<ACCOUNT_ID>:document/AwsAdvisorProbe*",
        "arn:aws:ec2:*:*:instance/*"
      ]
    },
    {
      "Sid": "AdvisorSsmProbeDocument",
      "Effect": "Allow",
      "Action": [
        "ssm:DescribeDocument",
        "ssm:GetDocument"
      ],
      "Resource": "arn:aws:ssm:*:<ACCOUNT_ID>:document/AwsAdvisorProbe*"
    },
    {
      "Sid": "AdvisorSsmProbeResults",
      "Effect": "Allow",
      "Action": [
        "ssm:GetCommandInvocation",
        "ssm:ListCommandInvocations"
      ],
      "Resource": "*"
    }
  ]
}
JSON
)

# Trust policy of the read-only role: who may assume it.
TRUST_JSON=$(cat <<'JSON'
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AdvisorParent",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::888722792401:role/aws-advisor-read"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
JSON
)

# The assume-only policy: the single permission the key (or the instance role) holds.
ASSUME_JSON=$(cat <<'JSON'
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "sts:AssumeRole",
      "Resource": "arn:aws:iam::<ACCOUNT_ID>:role/aws-advisor-read"
    }
  ]
}
JSON
)

# The SSM Command documents, one per probe kind, each embedding its read-only script (GET /api/probes/<kind>/document, aws-advisor/2.0).
PROBE_DOCUMENT_JSON_HOST=$(cat <<'JSON'
{
  "schemaVersion": "2.2",
  "description": "aws-advisor probe host 2.0 693b3df5 (read-only)",
  "parameters": {},
  "mainSteps": [
    {
      "action": "aws:runShellScript",
      "name": "probe_host",
      "inputs": {
        "timeoutSeconds": "60",
        "runCommand": [
          "# aws-advisor probe host 2.0 (read-only). Prints exactly one JSON object on the last line.",
          "set -u",
          "LC_ALL=C; export LC_ALL",
          "esc() { printf '%s' \"$1\" | sed 's/\\\\/\\\\\\\\/g; s/\"/\\\\\"/g'; }",
          "jstr() { if [ -n \"$1\" ]; then printf '\"%s\"' \"$(esc \"$1\")\"; else printf 'null'; fi; }",
          "hn=$(esc \"$(hostname 2>/dev/null || cat /etc/hostname 2>/dev/null || echo unknown)\"); now=$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "mem_total=$(awk '/^MemTotal:/{printf \"%.0f\", $2*1024}' /proc/meminfo)",
          "mem_avail=$(awk '/^MemAvailable:/{printf \"%.0f\", $2*1024}' /proc/meminfo)",
          "[ -n \"$mem_avail\" ] || mem_avail=$(awk '/^MemFree:/{f=$2} /^Buffers:/{b=$2} /^Cached:/{c=$2} END{printf \"%.0f\", (f+b+c)*1024}' /proc/meminfo)",
          "mem_used=$((mem_total - mem_avail))",
          "swap_total=$(awk '/^SwapTotal:/{printf \"%.0f\", $2*1024}' /proc/meminfo)",
          "swap_free=$(awk '/^SwapFree:/{printf \"%.0f\", $2*1024}' /proc/meminfo)",
          "swap_used=$((swap_total - swap_free))",
          "read l1 l5 l15 rest < /proc/loadavg",
          "cpus=$(nproc 2>/dev/null || grep -c '^processor' /proc/cpuinfo)",
          "uptime_s=$(cut -d. -f1 /proc/uptime)",
          "# Which disk a mounted filesystem sits on: the partition's parent (or a device-mapper volume's single slave), then",
          "# the EBS volume id from the NVMe serial on Nitro (\"vol0123...\" -> \"vol-0123...\"); Xen disks have no serial, so",
          "# only the device name (xvda) is reported and the advisor matches it to the attachment (/dev/sda1).",
          "blk_of() { d=$(basename \"$(readlink -f \"$1\" 2>/dev/null || printf '%s' \"$1\")\"); [ -e \"/sys/class/block/$d\" ] || return 0",
          "  [ -e \"/sys/class/block/$d/partition\" ] && d=$(basename \"$(dirname \"$(readlink -f \"/sys/class/block/$d\")\")\")",
          "  if [ \"$(ls \"/sys/class/block/$d/slaves\" 2>/dev/null | wc -l | tr -d ' ')\" = 1 ]; then d=$(ls \"/sys/class/block/$d/slaves\"); [ -e \"/sys/class/block/$d/partition\" ] && d=$(basename \"$(dirname \"$(readlink -f \"/sys/class/block/$d\")\")\"); fi",
          "  printf '%s' \"$d\"; }",
          "vol_of() { s=$(tr -d ' ' < \"/sys/class/block/$1/device/serial\" 2>/dev/null); case \"$s\" in vol*) printf 'vol-%s' \"${s#vol}\";; esac; }",
          "n=\"\"",
          "disks=$(df -P -k 2>/dev/null | awk 'NR>1 && $1 !~ /^(tmpfs|devtmpfs|udev|overlay|squashfs|shm|none)$/ && $1 !~ /^\\/dev\\/loop/ && $2 > 0 {print $1 \"\\t\" $2 \"\\t\" $3 \"\\t\" $6}' | while IFS=\"$(printf '\\t')\" read -r f t u m; do",
          "  b=$(blk_of \"$f\"); v=\"\"; [ -n \"$b\" ] && v=$(vol_of \"$b\")",
          "  printf '%s{\"mount\":%s,\"filesystem\":%s,\"device\":%s,\"volume_id\":%s,\"total_bytes\":%.0f,\"used_bytes\":%.0f,\"used_pct\":%s}' \"$n\" \"$(jstr \"$m\")\" \"$(jstr \"$f\")\" \"$(jstr \"$b\")\" \"$(jstr \"$v\")\" \"$((t*1024))\" \"$((u*1024))\" \"$(awk -v u=\"$u\" -v t=\"$t\" 'BEGIN{printf \"%.1f\", u*100/t}')\"; n=\",\"",
          "done)",
          "pslist() { ps -eo pid,pcpu,pmem,rss,comm --sort=\"$1\" 2>/dev/null | awk 'NR>1 && NR<=6 {",
          "  c=$5; for(i=6;i<=NF;i++) c=c\" \"$i; gsub(/\\\\/,\"\\\\\\\\\",c); gsub(/\"/,\"\\\\\\\"\",c);",
          "  printf \"%s{\\\"pid\\\":%d,\\\"cpu_pct\\\":%.1f,\\\"mem_pct\\\":%.1f,\\\"rss_bytes\\\":%.0f,\\\"command\\\":\\\"%s\\\"}\", (n++?\",\":\"\"), $1, $2, $3, $4*1024, c }'; }",
          "top_cpu=$(pslist -pcpu)",
          "top_mem=$(pslist -rss)",
          "out=$(printf '{\"probe\":\"aws-advisor/host/2\",\"kind\":\"host\",\"hostname\":\"%s\",\"collected_at\":\"%s\",\"cpus\":%s,\"uptime_seconds\":%s,\"memory\":{\"total_bytes\":%s,\"used_bytes\":%s,\"available_bytes\":%s,\"swap_total_bytes\":%s,\"swap_used_bytes\":%s},\"load\":{\"1m\":%s,\"5m\":%s,\"15m\":%s},\"disks\":[%s],\"top_cpu\":[%s],\"top_mem\":[%s]}' \\",
          "  \"$hn\" \"$now\" \"${cpus:-0}\" \"${uptime_s:-0}\" \"${mem_total:-0}\" \"${mem_used:-0}\" \"${mem_avail:-0}\" \"${swap_total:-0}\" \"${swap_used:-0}\" \"$l1\" \"$l5\" \"$l15\" \"$disks\" \"$top_cpu\" \"$top_mem\")",
          "# ---- exactly one JSON object on the last line. GetCommandInvocation returns only the first 24,000 characters of stdout, so a big result",
          "# ---- prints the object gzip-compressed and base64-encoded on one marked line instead (probe 1.7); the advisor decodes it (parseProbeOutput).",
          "if [ ${#out} -gt 16000 ] && command -v gzip >/dev/null 2>&1 && command -v base64 >/dev/null 2>&1; then printf 'aws-advisor-gz:%s\\n' \"$(printf '%s' \"$out\" | gzip -c -9 | base64 | tr -d '\\n')\"; else printf '%s\\n' \"$out\"; fi"
        ]
      }
    }
  ]
}
JSON
)
PROBE_DOCUMENT_JSON_DOCKER=$(cat <<'JSON'
{
  "schemaVersion": "2.2",
  "description": "aws-advisor probe docker 2.0 53a9d199 (read-only)",
  "parameters": {
    "signals": {
      "type": "String",
      "description": "Use-signal patterns: name=regex entries joined by ;; (the advisor passes its current list; this default applies when a caller sends none).",
      "default": "login=log(ged)? ?in|sign(ed)?[- ]?in;;auth=authenticat|authoriz;;payment=payment|invoice|keysend;;message=sent message|new message|received message;;join=joined;;upload=upload;;write_request=\"(POST|PUT|PATCH|DELETE) ;;websocket=websocket|ws open;;subscribe=subscribe|checkout",
      "allowedPattern": "^[^\\n]*$"
    }
  },
  "mainSteps": [
    {
      "action": "aws:runShellScript",
      "name": "probe_docker",
      "inputs": {
        "timeoutSeconds": "90",
        "runCommand": [
          "# aws-advisor probe docker 2.0 (read-only). Prints exactly one JSON object on the last line.",
          "set -u",
          "LC_ALL=C; export LC_ALL",
          "esc() { printf '%s' \"$1\" | sed 's/\\\\/\\\\\\\\/g; s/\"/\\\\\"/g'; }",
          "jstr() { if [ -n \"$1\" ]; then printf '\"%s\"' \"$(esc \"$1\")\"; else printf 'null'; fi; }",
          "hn=$(esc \"$(hostname 2>/dev/null || cat /etc/hostname 2>/dev/null || echo unknown)\"); now=$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "containers=\"[]\"; docker_json='{\"available\":false,\"running\":0,\"total\":0}'",
          "if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then",
          "  stats=$(docker stats --no-stream --format '{{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.NetIO}}' 2>/dev/null || true)",
          "  clist=$(docker ps -a --format '{{.Names}}\t{{.Image}}\t{{.State}}\t{{.RunningFor}}' 2>/dev/null | head -40 | awk -F'\\t' -v stats=\"$stats\" 'BEGIN{ k=split(stats, L, \"\\n\"); for(i=1;i<=k;i++){ split(L[i],a,\"\\t\"); cpu[a[1]]=a[2]; mem[a[1]]=a[3]; memp[a[1]]=a[4]; net[a[1]]=a[5] } }",
          "    function esc(x){ gsub(/\\\\/,\"\\\\\\\\\",x); gsub(/\"/,\"\\\\\\\"\",x); return x }",
          "    function bytes(x,  v,u){ sub(/ \\/.*/,\"\",x); v=x+0; u=x; sub(/^[0-9.]+/,\"\",u); if(u==\"KiB\"||u==\"kB\"||u==\"KB\")v*=1024; else if(u==\"MiB\"||u==\"MB\")v*=1048576; else if(u==\"GiB\"||u==\"GB\")v*=1073741824; else if(u==\"TiB\"||u==\"TB\")v*=1099511627776; return v }",
          "    function txb(x){ sub(/^.*\\/ */,\"\",x); return bytes(x) }",
          "    { n++; c=cpu[$1]; sub(/%/,\"\",c); mp=memp[$1]; sub(/%/,\"\",mp);",
          "      printf \"%s{\\\"name\\\":\\\"%s\\\",\\\"image\\\":\\\"%s\\\",\\\"state\\\":\\\"%s\\\",\\\"running_for\\\":\\\"%s\\\",\\\"cpu_pct\\\":%s,\\\"mem_bytes\\\":%.0f,\\\"mem_pct\\\":%s,\\\"net_rx_bytes\\\":%.0f,\\\"net_tx_bytes\\\":%.0f}\", (n>1?\",\":\"\"), esc($1), esc($2), esc($3), esc($4), (c==\"\"?\"null\":c), bytes(mem[$1]), (mp==\"\"?\"null\":mp), bytes(net[$1]), txb(net[$1]) }')",
          "  containers=\"[$clist]\"",
          "  running=$(docker ps -q 2>/dev/null | wc -l | tr -d ' '); total=$(docker ps -aq 2>/dev/null | wc -l | tr -d ' ')",
          "  docker_json=\"{\\\"available\\\":true,\\\"running\\\":${running:-0},\\\"total\\\":${total:-0}}\"",
          "fi",
          "# ---- activity (probe 1.4): is anyone actually using this box? Counts and timestamps only; log text stays on the box,",
          "# ---- except the last three lines of each container (capped, printable ASCII), shown in the UI and never sent to a model.",
          "# the patterns come from the document parameter `signals` (Settings > Probe pass); the advisor passes the current list on every probe",
          "SIGS=$(printf '%s' '{{ signals }}' | sed 's/;;/\\n/g')",
          "SIG_RE=$(printf '%s\\n' \"$SIGS\" | cut -d= -f2- | paste -sd'|' -)",
          "HB_RE='(health|ping|pong|heartbeat|keepalive|/metrics|/status|readiness|liveness|ELB-HealthChecker|swarm-checker|UptimeRobot|kube-probe)'",
          "ts_of() { printf '%s' \"$1\" | grep -oE '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}' | head -n 1; }",
          "jts() { t=$(ts_of \"$1\"); if [ -n \"$t\" ]; then printf '\"%sZ\"' \"$t\"; else printf 'null'; fi; }",
          "act_containers=\"\"; act_front='{\"source\":null,\"requests\":0,\"health\":0,\"last_request_at\":null,\"last_request_raw\":null,\"window\":null}'",
          "if docker info >/dev/null 2>&1; then",
          "  n=\"\"",
          "  for c in $(docker ps --format '{{.Names}}' 2>/dev/null | head -20); do",
          "    logs=$(docker logs --since 24h --tail 2000 --timestamps \"$c\" 2>&1 | tr -cd '\\12\\40-\\176')",
          "    lines=$(printf '%s\\n' \"$logs\" | grep -c .)",
          "    last_log=$(printf '%s\\n' \"$logs\" | grep . | tail -n 1)",
          "    errs=$(printf '%s\\n' \"$logs\" | grep -ciE '\\b(error|err|fatal|panic|exception)\\b')",
          "    warns=$(printf '%s\\n' \"$logs\" | grep -ciE '\\b(warn|warning)\\b')",
          "    clean=$(printf '%s\\n' \"$logs\" | grep -viE \"$HB_RE\" | grep -viE '\\b(error|exception|traceback|panic|fatal)\\b|^[^ ]+ +(from |at )')",
          "    sig=$(printf '%s\\n' \"$clean\" | grep -iE \"$SIG_RE\")",
          "    kinds=$(printf '%s\\n' \"$SIGS\" | while IFS='=' read -r nm re; do [ -n \"$nm\" ] || continue; k=$(printf '%s\\n' \"$clean\" | grep -ciE \"$re\"); [ \"${k:-0}\" -gt 0 ] && printf ',\"%s\":%s' \"$nm\" \"$k\"; done)",
          "    kinds=\"{${kinds#,}}\"",
          "    samples=$(printf '%s\\n' \"$sig\" | grep . | tail -n 60 | awk '{ $1=\"\"; sub(/^ /,\"\"); if(!($0 in seen)){ seen[$0]=1; out[++n]=$0 } } END { for(i=(n>5?n-4:1); i<=n; i++) print out[i] }' | cut -c1-160 | sed 's/\\\\/\\\\\\\\/g; s/\"/\\\\\"/g' | awk '{ printf \"%s\\\"%s\\\"\", (NR>1?\",\":\"\"), $0 }')",
          "    sigs=$(printf '%s\\n' \"$sig\" | grep -c .)",
          "    last_sig=$(printf '%s\\n' \"$sig\" | grep . | tail -n 1)",
          "    ins=$(docker inspect --format '{{.State.StartedAt}} {{.RestartCount}} {{.Config.Image}}' \"$c\" 2>/dev/null)",
          "    started=$(printf '%s' \"$ins\" | awk '{print $1}'); restarts=$(printf '%s' \"$ins\" | awk '{print $2}'); img=$(printf '%s' \"$ins\" | awk '{print $3}')",
          "    tail3=$(printf '%s\\n' \"$logs\" | grep . | tail -n 3 | cut -c1-160 | sed 's/\\\\/\\\\\\\\/g; s/\"/\\\\\"/g' | awk '{ printf \"%s\\\"%s\\\"\", (NR>1?\",\":\"\"), $0 }')",
          "    case \"$img\" in *nginx*|*caddy*|*traefik*|*haproxy*|*proxy*|*ingress*)",
          "      if [ \"$act_front\" = '{\"source\":null,\"requests\":0,\"health\":0,\"last_request_at\":null,\"last_request_raw\":null,\"window\":null}' ]; then",
          "        acc=$(printf '%s\\n' \"$logs\" | grep -E '\" [0-9]{3} |HTTP/[0-9.]+\" [0-9]{3}|\"status\":[0-9]{3}|status=[0-9]{3}')",
          "        reqs=$(printf '%s\\n' \"$acc\" | grep -c .); hb=$(printf '%s\\n' \"$acc\" | grep -ciE \"$HB_RE\")",
          "        lastreq=$(printf '%s\\n' \"$acc\" | grep -viE \"$HB_RE\" | grep . | tail -n 1)",
          "        act_front=\"{\\\"source\\\":\\\"container:$(esc \"$c\")\\\",\\\"requests\\\":$((reqs - hb)),\\\"health\\\":${hb:-0},\\\"last_request_at\\\":$(jts \"$lastreq\"),\\\"last_request_raw\\\":null,\\\"window\\\":\\\"24h\\\"}\"",
          "      fi;;",
          "    esac",
          "    act_containers=\"$act_containers$n{\\\"name\\\":\\\"$(esc \"$c\")\\\",\\\"started_at\\\":$(jts \"$started\"),\\\"restarts\\\":${restarts:-0},\\\"log_lines\\\":${lines:-0},\\\"last_log_at\\\":$(jts \"$last_log\"),\\\"errors\\\":${errs:-0},\\\"warns\\\":${warns:-0},\\\"signal_lines\\\":${sigs:-0},\\\"last_signal_at\\\":$(jts \"$last_sig\"),\\\"last_lines\\\":[$tail3],\\\"signal_kinds\\\":$kinds,\\\"signal_samples\\\":[$samples]}\"",
          "    n=\",\"",
          "  done",
          "fi",
          "if [ \"$act_front\" = '{\"source\":null,\"requests\":0,\"health\":0,\"last_request_at\":null,\"last_request_raw\":null,\"window\":null}' ]; then",
          "  for f in /var/log/nginx/access.log /var/log/caddy/access.log /var/log/apache2/access.log /var/log/httpd/access_log; do",
          "    if [ -r \"$f\" ]; then",
          "      acc=$(tail -n 5000 \"$f\" 2>/dev/null | tr -cd '\\12\\40-\\176')",
          "      reqs=$(printf '%s\\n' \"$acc\" | grep -c .); hb=$(printf '%s\\n' \"$acc\" | grep -ciE \"$HB_RE\")",
          "      lastreq=$(printf '%s\\n' \"$acc\" | grep -viE \"$HB_RE\" | grep . | tail -n 1 | grep -oE '\\[[^]]+\\]' | head -n 1 | tr -d '[]')",
          "      act_front=\"{\\\"source\\\":\\\"file:$(esc \"$f\")\\\",\\\"requests\\\":$((reqs - hb)),\\\"health\\\":${hb:-0},\\\"last_request_at\\\":null,\\\"last_request_raw\\\":$(jstr \"$lastreq\"),\\\"window\\\":\\\"last 5000 lines\\\"}\"",
          "      break",
          "    fi",
          "  done",
          "fi",
          "# established TCP flows: conntrack sees the DNAT'd container traffic the host's own sockets do not; ss covers host services and ssh",
          "conns=\"\"; src=\"none\"",
          "if [ -r /proc/net/nf_conntrack ]; then conns=$(grep -E '^ipv[46] +[0-9]+ +tcp .*ESTABLISHED' /proc/net/nf_conntrack 2>/dev/null | awk '{ for(i=1;i<=NF;i++){ if($i ~ /^src=/ && s==\"\") s=substr($i,5); if($i ~ /^dport=/ && d==\"\") d=substr($i,7) } print s, d; s=\"\"; d=\"\" }'); src=\"conntrack\"",
          "elif command -v conntrack >/dev/null 2>&1; then conns=$(conntrack -L -p tcp --state ESTABLISHED 2>/dev/null | awk '{ for(i=1;i<=NF;i++){ if($i ~ /^src=/ && s==\"\") s=substr($i,5); if($i ~ /^dport=/ && d==\"\") d=substr($i,7) } print s, d; s=\"\"; d=\"\" }'); src=\"conntrack\"",
          "elif command -v ss >/dev/null 2>&1; then conns=$(ss -Htn state established 2>/dev/null | awk '{ l=$3; p=$4; sub(/.*:/,\"\",l); sub(/:[0-9]+$/,\"\",p); gsub(/[\\[\\]]/,\"\",p); sub(/^::ffff:/,\"\",p); print p, l }'); src=\"ss\"",
          "fi",
          "ssh_n=$(ss -Htn state established '( sport = :22 )' 2>/dev/null | grep -c .)",
          "# which container answers on each published host port, so a flow to :443 can be named",
          "port_map=$(docker ps --format '{{.Names}}\t{{.Ports}}' 2>/dev/null | awk -F'\t' '{ n=split($2, P, \", \"); for(i=1;i<=n;i++){ if(match(P[i], /:[0-9]+->/)){ hp=substr(P[i], RSTART+1, RLENGTH-3); if(!(hp in seen)){ seen[hp]=1; nm=$1; gsub(/[\"\\\\]/, \"\", nm); printf \"%s\\\"%s\\\":\\\"%s\\\"\", (c++?\",\":\"\"), hp, nm } } } }')",
          "act_conns=$(printf '%s\\n' \"$conns\" | awk -v src=\"$src\" -v ssh=\"${ssh_n:-0}\" -v pmap=\"$port_map\" '",
          "  function kind(ip){ if(ip==\"\" ) return \"x\"; if(ip ~ /^127\\./ || ip==\"::1\" || ip ~ /^169\\.254\\./ || ip ~ /^fe80/) return \"x\"; if(ip ~ /^172\\.(1[6-9]|2[0-9]|3[01])\\./) return \"x\"; if(ip ~ /^10\\./ || ip ~ /^192\\.168\\./) return \"internal\"; return \"external\" }",
          "  NF==2 { k=kind($1); if(k==\"x\") next; total++; if(k==\"external\") ext++; else int_++; ports[$2]++; peers[$1]=1; pair[$1 \" \" $2]++; pk[$1 \" \" $2]=k }",
          "  END { np=0; for(p in ports) np++; printf \"{\\\"source\\\":\\\"%s\\\",\\\"established\\\":%d,\\\"external\\\":%d,\\\"internal\\\":%d,\\\"peers\\\":%d,\\\"ssh\\\":%d,\\\"by_port\\\":{\", src, total, ext, int_, length(peers), ssh; first=1; for(p in ports){ if(p ~ /^[0-9]+$/){ printf \"%s\\\"%s\\\":%d\", (first?\"\":\",\"), p, ports[p]; first=0 } }",
          "    printf \"},\\\"top_peers\\\":[\"; for(t=0;t<8;t++){ best=\"\"; bn=0; for(q in pair){ if(!(q in done) && pair[q]>bn){ best=q; bn=pair[q] } } if(best==\"\") break; done[best]=1; split(best, ab, \" \"); if(ab[2] !~ /^[0-9]+$/) continue; printf \"%s{\\\"ip\\\":\\\"%s\\\",\\\"port\\\":%d,\\\"flows\\\":%d,\\\"kind\\\":\\\"%s\\\"}\", (t?\",\":\"\"), ab[1], ab[2], bn, pk[best] }",
          "    printf \"],\\\"port_map\\\":{%s}}\", pmap }')",
          "users_now=$(who 2>/dev/null | grep -c .)",
          "lastl=$(last -n 8 --time-format iso 2>/dev/null | grep -vE '^(reboot|shutdown|wtmp|btmp|$)' | head -n 1)",
          "last_user=$(printf '%s' \"$lastl\" | awk '{print $1}'); last_at=$(printf '%s' \"$lastl\" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[+-][0-9]{2}:?[0-9]{2}' | head -n 1)",
          "act_logins=\"{\\\"users_now\\\":${users_now:-0},\\\"last_login_user\\\":$(jstr \"$last_user\"),\\\"last_login_at\\\":$(jstr \"$last_at\")}\"",
          "act_net=$(awk -F'[: ]+' 'NR>2 && $2 !~ /^(lo|docker|br-|veth|virbr)/ { rx+=$3; tx+=$11 } END { printf \"{\\\"rx_bytes\\\":%.0f,\\\"tx_bytes\\\":%.0f}\", rx, tx }' /proc/net/dev 2>/dev/null)",
          "activity=\"{\\\"version\\\":1,\\\"containers\\\":[$act_containers],\\\"connections\\\":${act_conns:-null},\\\"front_door\\\":$act_front,\\\"logins\\\":$act_logins,\\\"net\\\":${act_net:-null}}\"",
          "out=$(printf '{\"probe\":\"aws-advisor/docker/2\",\"kind\":\"docker\",\"hostname\":\"%s\",\"collected_at\":\"%s\",\"docker\":%s,\"containers\":%s,\"activity\":%s}' \"$hn\" \"$now\" \"$docker_json\" \"$containers\" \"$activity\")",
          "# ---- exactly one JSON object on the last line. GetCommandInvocation returns only the first 24,000 characters of stdout, so a big result",
          "# ---- prints the object gzip-compressed and base64-encoded on one marked line instead (probe 1.7); the advisor decodes it (parseProbeOutput).",
          "if [ ${#out} -gt 16000 ] && command -v gzip >/dev/null 2>&1 && command -v base64 >/dev/null 2>&1; then printf 'aws-advisor-gz:%s\\n' \"$(printf '%s' \"$out\" | gzip -c -9 | base64 | tr -d '\\n')\"; else printf '%s\\n' \"$out\"; fi"
        ]
      }
    }
  ]
}
JSON
)
PROBE_DOCUMENT_JSON_APPS=$(cat <<'JSON'
{
  "schemaVersion": "2.2",
  "description": "aws-advisor probe apps 2.0 91714a98 (read-only)",
  "parameters": {},
  "mainSteps": [
    {
      "action": "aws:runShellScript",
      "name": "probe_apps",
      "inputs": {
        "timeoutSeconds": "60",
        "runCommand": [
          "# aws-advisor probe apps 2.0 (read-only). Prints exactly one JSON object on the last line.",
          "set -u",
          "LC_ALL=C; export LC_ALL",
          "esc() { printf '%s' \"$1\" | sed 's/\\\\/\\\\\\\\/g; s/\"/\\\\\"/g'; }",
          "jstr() { if [ -n \"$1\" ]; then printf '\"%s\"' \"$(esc \"$1\")\"; else printf 'null'; fi; }",
          "hn=$(esc \"$(hostname 2>/dev/null || cat /etc/hostname 2>/dev/null || echo unknown)\"); now=$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "# ---- log shipping (probe 1.6): the CloudWatch log groups this box's agents are configured to write to, read from their config files",
          "# ---- (CloudWatch agent, the old awslogs agent, Fluent Bit, Fluentd, the Docker daemon and each running container with the awslogs driver). Templated names are skipped.",
          "# ---- Quoting note: the setup script embeds this document in a bash heredoc inside $( ), so single quotes must pair up on every line and never sit alone in a comment.",
          "ship=\"\"; shipn=\"\"; shipseen=\"|\"",
          "addship() { g=$(printf '%s' \"$1\" | tr -d '\"\\047,; ' | cut -c1-200); [ -n \"$g\" ] || return 0; case \"$g\" in *\\$*|*\\{*|*%*) return 0;; esac",
          "  case \"$shipseen\" in *\"|$2=$g|\"*) return 0;; esac; shipseen=\"$shipseen$2=$g|\"",
          "  ship=\"$ship$shipn{\\\"group\\\":\\\"$(esc \"$g\")\\\",\\\"via\\\":\\\"$(esc \"$2\")\\\",\\\"source\\\":\\\"$(esc \"$3\")\\\"}\"; shipn=\",\"; }",
          "for f in /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/* /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml /etc/awslogs/awslogs.conf /var/awslogs/etc/awslogs.conf /etc/fluent-bit/*.conf /etc/fluent-bit/*.yaml /etc/fluent-bit/*.yml /etc/fluent-bit/conf.d/* /etc/td-agent-bit/*.conf /etc/td-agent/td-agent.conf /etc/fluent/fluent.conf /etc/fluentd/fluent.conf; do",
          "  [ -r \"$f\" ] || continue",
          "  case \"$f\" in *amazon-cloudwatch-agent*) via=cloudwatch-agent;; *awslogs*) via=awslogs;; *fluent-bit*|*td-agent-bit*) via=fluent-bit;; *) via=fluentd;; esac",
          "  for g in $(grep -ioE 'log_group_name\"?[[:space:]]*[:=]?[[:space:]]*\"?[^\",[:space:]]+' \"$f\" 2>/dev/null | sed -E 's/^[^:=[:space:]]+[[:space:]]*[:=]?[[:space:]]*\"?//' | head -n 50); do addship \"$g\" \"$via\" \"$f\"; done",
          "done",
          "if [ -r /etc/docker/daemon.json ]; then for g in $(grep -oE '\"awslogs-group\"[[:space:]]*:[[:space:]]*\"[^\"]+\"' /etc/docker/daemon.json 2>/dev/null | sed -E 's/^.*:[[:space:]]*\"//; s/\"$//'); do addship \"$g\" docker-daemon /etc/docker/daemon.json; done; fi",
          "if docker info >/dev/null 2>&1; then for c in $(docker ps --format '{{.Names}}' 2>/dev/null | head -40); do l=$(docker inspect --format '{{.HostConfig.LogConfig.Type}} {{index .HostConfig.LogConfig.Config \"awslogs-group\"}}' \"$c\" 2>/dev/null); case \"$l\" in \"awslogs \"?*) addship \"${l#awslogs }\" \"docker:$c\" 'log driver';; esac; done; fi",
          "# ---- processes (probe 1.6): every user-space process grouped by command and user, so the advisor knows what runs on the box. Kernel threads",
          "# ---- are left out here; the advisor sets the OS daemons aside (src/instance_apps.ts). Names, counts, CPU, memory and age only: no arguments beyond the program and its first words.",
          "procs=$(ps -eo pid,ppid,user,pcpu,rss,etimes,comm,args --no-headers 2>/dev/null | tr -cd '\\12\\40-\\176' | awk '",
          "  $1==2 || $2==2 { next }",
          "  { w=\"\"; if($7 ~ /^(python[0-9.]*|node|nodejs|java|ruby|php[0-9.]*|perl|dotnet|bun|deno|uwsgi|gunicorn|celery|npm|yarn|pnpm)$/){ for(i=9;i<=NF && i<=14;i++) if($i !~ /^-/){ w=$i; sub(/.*\\//,\"\",w); break } }",
          "    nm=(w==\"\"?$7:$7 \" \" w); k=$3 \"\\t\" nm; n[k]++; cpu[k]+=$4; rss[k]+=$5; if($6+0>old[k]) old[k]=$6+0; if(!(k in a)){ a[k]=$8; for(i=9;i<=NF && i<=12;i++) a[k]=a[k] \" \" $i } }",
          "  END { for(k in n){ split(k, p, \"\\t\"); cmd=substr(a[k],1,120); gsub(/[\\\\\"]/,\"\",cmd); c=p[2]; gsub(/[\\\\\"]/,\"\",c); u=p[1]; gsub(/[\\\\\"]/,\"\",u);",
          "    printf \"%012.0f\\t{\\\"name\\\":\\\"%s\\\",\\\"user\\\":\\\"%s\\\",\\\"count\\\":%d,\\\"cpu_pct\\\":%.1f,\\\"rss_bytes\\\":%.0f,\\\"oldest_seconds\\\":%d,\\\"command\\\":\\\"%s\\\"}\\n\", rss[k]*1024, c, u, n[k], cpu[k], rss[k]*1024, old[k], cmd } }' | sort -rn | head -n 80 | cut -f2- | paste -sd, -)",
          "# ---- listeners (probe 1.8): every port the box answers on and which program owns it, from the listening sockets (ss) and the ports",
          "# ---- containers publish (docker ps). scope: all = every interface, loopback = the box only, address = one interface. The advisor matches",
          "# ---- each port to the app or container behind it and to the security group rules that let traffic in (src/instance_apps.ts).",
          "lsn=\"\"; dports=\"\"",
          "if command -v ss >/dev/null 2>&1; then lsn=$(ss -Hlntup 2>/dev/null | tr -cd '\\12\\40-\\176' | awk '{ proto=$1; if(proto!=\"tcp\" && proto!=\"udp\") next; l=$5; p=l; sub(/.*:/,\"\",p); if(p !~ /^[0-9]+$/) next; a=l; sub(/:[0-9]+$/,\"\",a); gsub(/[\\[\\]]/,\"\",a); sub(/%.*/,\"\",a); if(a==\"*\"||a==\"0.0.0.0\"||a==\"::\"||a==\"\") s=\"all\"; else if(a ~ /^127\\./||a==\"::1\") s=\"loopback\"; else s=\"address\"; nm=\"\"; pid=\"\"; if(match($0,/users:\\(\\(\"[^\"]*\",pid=[0-9]+/)){ u=substr($0,RSTART,RLENGTH); nm=u; sub(/^users:\\(\\(\"/,\"\",nm); sub(/\",pid=.*/,\"\",nm); pid=u; sub(/.*pid=/,\"\",pid) } k=proto \":\" p \":\" a; if(k in seen) next; seen[k]=1; n++; if(n>80) exit; gsub(/[\\\\\"]/,\"\",nm); printf \"%s{\\\"proto\\\":\\\"%s\\\",\\\"port\\\":%d,\\\"bind\\\":\\\"%s\\\",\\\"scope\\\":\\\"%s\\\",\\\"process\\\":%s,\\\"pid\\\":%s,\\\"container\\\":null,\\\"container_port\\\":null}\", (n>1?\",\":\"\"), proto, p, a, s, (nm==\"\"?\"null\":\"\\\"\" nm \"\\\"\"), (pid==\"\"?\"null\":pid) }'); fi",
          "dports=$(docker ps --format '{{.Names}}\\t{{.Ports}}' 2>/dev/null | awk -F'\\t' '{ n=split($2, P, \", \"); for(i=1;i<=n;i++){ if(match(P[i], /:[0-9]+->[0-9]+\\/(tcp|udp)/)){ m=substr(P[i],RSTART+1,RLENGTH-1); hp=m; sub(/->.*/,\"\",hp); cp=m; sub(/.*->/,\"\",cp); pr=cp; sub(/.*\\//,\"\",pr); sub(/\\/.*/,\"\",cp); b=P[i]; sub(/:[0-9]+->.*/,\"\",b); gsub(/[\\[\\]]/,\"\",b); if(b==\"0.0.0.0\"||b==\"::\"||b==\"\") s=\"all\"; else if(b ~ /^127\\./) s=\"loopback\"; else s=\"address\"; nm=$1; gsub(/[\\\\\"]/,\"\",nm); k=pr \":\" hp; if(k in seen) continue; seen[k]=1; c++; if(c>80) exit; printf \"%s{\\\"proto\\\":\\\"%s\\\",\\\"port\\\":%d,\\\"bind\\\":\\\"%s\\\",\\\"scope\\\":\\\"%s\\\",\\\"process\\\":null,\\\"pid\\\":null,\\\"container\\\":\\\"%s\\\",\\\"container_port\\\":%d}\", (c>1?\",\":\"\"), pr, hp, b, s, nm, cp } } }')",
          "listeners=\"$lsn\"; if [ -n \"$lsn\" ] && [ -n \"$dports\" ]; then listeners=\"$lsn,$dports\"; elif [ -z \"$lsn\" ]; then listeners=\"$dports\"; fi",
          "out=$(printf '{\"probe\":\"aws-advisor/apps/2\",\"kind\":\"apps\",\"hostname\":\"%s\",\"collected_at\":\"%s\",\"log_shipping\":[%s],\"processes\":[%s],\"listeners\":[%s]}' \"$hn\" \"$now\" \"$ship\" \"$procs\" \"$listeners\")",
          "# ---- exactly one JSON object on the last line. GetCommandInvocation returns only the first 24,000 characters of stdout, so a big result",
          "# ---- prints the object gzip-compressed and base64-encoded on one marked line instead (probe 1.7); the advisor decodes it (parseProbeOutput).",
          "if [ ${#out} -gt 16000 ] && command -v gzip >/dev/null 2>&1 && command -v base64 >/dev/null 2>&1; then printf 'aws-advisor-gz:%s\\n' \"$(printf '%s' \"$out\" | gzip -c -9 | base64 | tr -d '\\n')\"; else printf '%s\\n' \"$out\"; fi"
        ]
      }
    }
  ]
}
JSON
)
PROBE_DOCUMENT_JSON_SOFTWARE=$(cat <<'JSON'
{
  "schemaVersion": "2.2",
  "description": "aws-advisor probe software 1.0 90e8474c (read-only)",
  "parameters": {},
  "mainSteps": [
    {
      "action": "aws:runShellScript",
      "name": "probe_software",
      "inputs": {
        "timeoutSeconds": "120",
        "runCommand": [
          "# aws-advisor probe software 1.0 (read-only). Prints exactly one JSON object on the last line.",
          "set -u",
          "LC_ALL=C; export LC_ALL",
          "esc() { printf '%s' \"$1\" | sed 's/\\\\/\\\\\\\\/g; s/\"/\\\\\"/g'; }",
          "jstr() { if [ -n \"$1\" ]; then printf '\"%s\"' \"$(esc \"$1\")\"; else printf 'null'; fi; }",
          "hn=$(esc \"$(hostname 2>/dev/null || cat /etc/hostname 2>/dev/null || echo unknown)\"); now=$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "# ---- software (probe 2.0): what is installed and which version, for vulnerability matching. Read-only: package database, /etc/os-release,",
          "# ---- uname, the version flag of well-known programs, and the images of the running containers. Names and versions only; nothing is executed beyond --version.",
          "os_id=\"\"; os_ver=\"\"; os_name=\"\"",
          "if [ -r /etc/os-release ]; then os_id=$(. /etc/os-release 2>/dev/null; printf '%s' \"${ID:-}\"); os_ver=$(. /etc/os-release 2>/dev/null; printf '%s' \"${VERSION_ID:-}\"); os_name=$(. /etc/os-release 2>/dev/null; printf '%s' \"${PRETTY_NAME:-}\"); fi",
          "kernel=$(uname -r 2>/dev/null); arch=$(uname -m 2>/dev/null)",
          "pm=\"\"; pkgs=\"\"",
          "# every installed package: name, version, architecture and, when it differs from the name, the source package (s): the distribution advisories (OSV, USN, DSA) name the source, openssh, not the binary, openssh-server",
          "if command -v dpkg-query >/dev/null 2>&1; then pm=deb; pkgs=$(dpkg-query -W -f='${db:Status-Abbrev}\\t${Package}\\t${Version}\\t${Architecture}\\t${source:Package}\\n' 2>/dev/null | tr -cd '\\11\\12\\40-\\176' | awk -F'\\t' '$1 ~ /^.i/ { gsub(/[\\\\\"]/,\"\",$2); gsub(/[\\\\\"]/,\"\",$3); gsub(/[\\\\\"]/,\"\",$4); gsub(/[\\\\\" ]/,\"\",$5); printf \"%s{\\\"n\\\":\\\"%s\\\",\\\"v\\\":\\\"%s\\\",\\\"a\\\":\\\"%s\\\"%s}\", (n++?\",\":\"\"), $2, $3, $4, ($5!=\"\" && $5!=$2 ? \",\\\"s\\\":\\\"\" $5 \"\\\"\" : \"\") }')",
          "elif command -v rpm >/dev/null 2>&1; then pm=rpm; pkgs=$(rpm -qa --qf '%{NAME}\\t%{EPOCH}:%{VERSION}-%{RELEASE}\\t%{ARCH}\\t%{SOURCERPM}\\n' 2>/dev/null | tr -cd '\\11\\12\\40-\\176' | awk -F'\\t' '{ v=$2; sub(/^\\(none\\):/,\"\",v); s=$4; sub(/-[^-]*-[^-]*\\.src\\.rpm$/,\"\",s); gsub(/[\\\\\"]/,\"\",$1); gsub(/[\\\\\"]/,\"\",v); gsub(/[\\\\\"]/,\"\",$3); gsub(/[\\\\\"]/,\"\",s); printf \"%s{\\\"n\\\":\\\"%s\\\",\\\"v\\\":\\\"%s\\\",\\\"a\\\":\\\"%s\\\"%s}\", (n++?\",\":\"\"), $1, v, $3, (s!=\"\" && s!=$1 && s!=\"(none)\" ? \",\\\"s\\\":\\\"\" s \"\\\"\" : \"\") }')",
          "elif command -v apk >/dev/null 2>&1; then pm=apk; pkgs=$( (apk list -I 2>/dev/null || apk info -v 2>/dev/null) | tr -cd '\\12\\40-\\176' | awk '{ p=$1; gsub(/[\\\\\"]/,\"\",p); if(match(p,/-[0-9][^-]*(-r[0-9]+)?$/)){ n=substr(p,1,RSTART-1); v=substr(p,RSTART+1) } else { n=p; v=\"\" } s=\"\"; if(match($0,/\\{[^}]*\\}/)){ s=substr($0,RSTART+1,RLENGTH-2); gsub(/[\\\\\"]/,\"\",s) } printf \"%s{\\\"n\\\":\\\"%s\\\",\\\"v\\\":\\\"%s\\\",\\\"a\\\":\\\"\\\"%s}\", (c++?\",\":\"\"), n, v, (s!=\"\" && s!=n ? \",\\\"s\\\":\\\"\" s \"\\\"\" : \"\") }')",
          "fi",
          "# the version string of the programs a CVE usually names, from the binary itself (one line, printable ASCII, 100 chars)",
          "bins=\"\"; bn=\"\"",
          "vof() { \"$@\" 2>&1 </dev/null | head -n 1 | tr -cd '\\40-\\176' | cut -c1-100; }",
          "addbin() { [ -n \"$2\" ] || return 0; bins=\"$bins$bn{\\\"name\\\":\\\"$(esc \"$1\")\\\",\\\"version\\\":\\\"$(esc \"$2\")\\\",\\\"path\\\":\\\"$(esc \"$3\")\\\"}\"; bn=\",\"; }",
          "for b in sshd nginx apache2 httpd openssl node nodejs python3 python docker containerd postgres redis-server mysqld mariadbd mongod java ruby go caddy haproxy traefik bitcoind lnd php perl git curl; do",
          "  p=$(command -v \"$b\" 2>/dev/null) || continue; v=\"\"",
          "  case \"$b\" in sshd) v=$(vof ssh -V);; openssl) v=$(vof \"$p\" version);; go) v=$(vof \"$p\" version);; java) v=$(vof \"$p\" -version);; apache2|httpd) v=$(vof \"$p\" -v);; *) v=$(vof \"$p\" --version);; esac",
          "  addbin \"$b\" \"$v\" \"$p\"",
          "done",
          "# the images behind the running containers: name, id, digest, build date, platform",
          "imgs=\"\"",
          "if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then imgs=$(docker ps --format '{{.Image}}' 2>/dev/null | sort -u | head -60 | while read -r im; do [ -n \"$im\" ] || continue; ins=$(docker image inspect --format '{{.Id}}|{{join .RepoDigests \",\"}}|{{.Created}}|{{.Os}}/{{.Architecture}}' \"$im\" 2>/dev/null | head -n 1); printf '%s\\t%s\\n' \"$im\" \"$ins\"; done | tr -cd '\\11\\12\\40-\\176' | awk -F'\\t' '{ split($2, f, \"|\"); gsub(/[\\\\\"]/,\"\",$1); gsub(/[\\\\\"]/,\"\",f[2]); printf \"%s{\\\"image\\\":\\\"%s\\\",\\\"id\\\":\\\"%s\\\",\\\"digests\\\":\\\"%s\\\",\\\"created\\\":\\\"%s\\\",\\\"platform\\\":\\\"%s\\\"}\", (n++?\",\":\"\"), $1, f[1], f[2], f[3], f[4] }'); fi",
          "out=$(printf '{\"probe\":\"aws-advisor/software/2\",\"kind\":\"software\",\"hostname\":\"%s\",\"collected_at\":\"%s\",\"os\":{\"id\":%s,\"version\":%s,\"name\":%s},\"kernel\":%s,\"arch\":%s,\"package_manager\":%s,\"packages\":[%s],\"binaries\":[%s],\"images\":[%s]}' \\",
          "  \"$hn\" \"$now\" \"$(jstr \"$os_id\")\" \"$(jstr \"$os_ver\")\" \"$(jstr \"$os_name\")\" \"$(jstr \"$kernel\")\" \"$(jstr \"$arch\")\" \"$(jstr \"$pm\")\" \"$pkgs\" \"$bins\" \"$imgs\")",
          "# ---- exactly one JSON object on the last line. GetCommandInvocation returns only the first 24,000 characters of stdout, so a big result",
          "# ---- prints the object gzip-compressed and base64-encoded on one marked line instead (probe 1.7); the advisor decodes it (parseProbeOutput).",
          "if [ ${#out} -gt 16000 ] && command -v gzip >/dev/null 2>&1 && command -v base64 >/dev/null 2>&1; then printf 'aws-advisor-gz:%s\\n' \"$(printf '%s' \"$out\" | gzip -c -9 | base64 | tr -d '\\n')\"; else printf '%s\\n' \"$out\"; fi"
        ]
      }
    }
  ]
}
JSON
)

# ---- helpers ------------------------------------------------------------------------------------------------------
note() { printf '    %s\n' "$*"; }
warn() { printf '    WARNING: %s\n' "$*" >&2; }
die()  { printf '\nERROR: %s\n' "$*" >&2; exit 1; }
STEP=0
step() { STEP=$((STEP + 1)); printf '\n==> step %d/%d: %s\n' "$STEP" "$TOTAL_STEPS" "$1"; }

# Prints its arguments shell-quoted, for the dry-run lines.
fmt() {
  local out="" a
  for a in "$@"; do
    case "$a" in
      *[!A-Za-z0-9_./:=@,+-]*|"") out="$out '$(printf '%s' "$a" | sed "s/'/'\\''/g")'" ;;
      *) out="$out $a" ;;
    esac
  done
  printf '%s' "${out# }"
}

# aws with the admin profile. Never used for `aws configure`, whose --profile is the profile being written.
aws_admin() {
  if [ -n "$ADMIN_PROFILE" ]; then aws --profile "$ADMIN_PROFILE" "$@"; else aws "$@"; fi
}
# The same call as one printable line, for the dry run.
fmt_admin() {
  if [ -n "$ADMIN_PROFILE" ]; then fmt aws --profile "$ADMIN_PROFILE" "$@"; else fmt aws "$@"; fi
}
# A command that changes something: run (stdout discarded), or printed in a dry run.
run() {
  if [ "$DRY_RUN" = 1 ]; then printf '    + %s\n' "$(fmt_admin "$@")"; return 0; fi
  if aws_admin "$@" >/dev/null 2>"$WORK/err"; then return 0; fi
  die "$(fmt_admin "$@") failed: $(cat "$WORK/err")"
}
# run_when_principal_resolves <aws args>: like run, but a MalformedPolicyDocument "Invalid principal" answer is IAM not
# having propagated a user or role created seconds ago; wait and retry for up to two minutes before giving up.
run_when_principal_resolves() {
  if [ "$DRY_RUN" = 1 ]; then printf '    + %s\n' "$(fmt_admin "$@")"; return 0; fi
  local attempt=0
  while :; do
    if aws_admin "$@" >/dev/null 2>"$WORK/err"; then return 0; fi
    if grep -q "Invalid principal" "$WORK/err" && [ "$attempt" -lt 24 ]; then
      attempt=$((attempt + 1)); [ "$attempt" -eq 1 ] && note "the principal is not visible to IAM yet (it was just created); waiting for it to propagate..."
      sleep 5; continue
    fi
    die "$(fmt_admin "$@") failed: $(cat "$WORK/err")"
  done
}
# A read-only call whose output the script needs. Dry run: printed (to stderr, so it is not captured), outputs nothing.
query() {
  if [ "$DRY_RUN" = 1 ]; then printf '    + (query) %s\n' "$(fmt_admin "$@")" >&2; return 0; fi
  aws_admin "$@"
}
# exists <aws args>: 0 when the resource exists, 1 when AWS says it does not, abort on any other error. Dry run: 1.
exists() {
  if [ "$DRY_RUN" = 1 ]; then printf '    + (check) %s\n' "$(fmt_admin "$@")"; return 1; fi
  if aws_admin "$@" >/dev/null 2>"$WORK/err"; then return 0; fi
  case "$(cat "$WORK/err")" in
    *NoSuchEntity*|*InvalidDocument*|*NotFound*|*"does not exist"*|*InvalidInstanceID*) return 1 ;;
  esac
  die "$(fmt_admin "$@") failed: $(cat "$WORK/err")"
}
# aws configure set on the profile the script writes (no admin profile here).
configure_set() {
  if [ "$DRY_RUN" = 1 ]; then printf '    + %s\n' "$(fmt aws configure set --profile "$1" "$2" "$3")"; return 0; fi
  aws configure set --profile "$1" "$2" "$3"
}
# Whitespace-insensitive comparison of two JSON documents.
squeeze() { tr -d ' \t\r\n'; }

# Writes the embedded documents with the account id filled in.
write_documents() {
  printf '%s\n' "$POLICY_JSON" | sed "s/<ACCOUNT_ID>/$ACCOUNT_ID/g" > "$WORK/policy.json"
  printf '%s\n' "$TRUST_JSON" | sed "s/<ACCOUNT_ID>/$ACCOUNT_ID/g" > "$WORK/trust.json"
  printf '%s\n' "$ASSUME_JSON" | sed "s/<ACCOUNT_ID>/$ACCOUNT_ID/g" > "$WORK/assume.json"
  [ -z "${EC2_TRUST_JSON:-}" ] || printf '%s\n' "$EC2_TRUST_JSON" > "$WORK/ec2-trust.json"
  printf '%s\n' "$PROBE_DOCUMENT_JSON_HOST" > "$WORK/probe-host.json"
  printf '%s\n' "$PROBE_DOCUMENT_JSON_DOCKER" > "$WORK/probe-docker.json"
  printf '%s\n' "$PROBE_DOCUMENT_JSON_APPS" > "$WORK/probe-apps.json"
  printf '%s\n' "$PROBE_DOCUMENT_JSON_SOFTWARE" > "$WORK/probe-software.json"
  PRINCIPAL_ARN=$(printf '%s' "$PRINCIPAL_ARN" | sed "s/<ACCOUNT_ID>/$ACCOUNT_ID/g")
  [ "$DRY_RUN" = 1 ] && note "documents written to $WORK (policy.json, trust.json, assume.json, probe-host.json, probe-docker.json, probe-apps.json, probe-software.json); kept after the dry run for inspection"
  true
}

# ensure_trust ROLE PRINCIPAL_ARN SID: the role's trust policy gets a statement letting PRINCIPAL_ARN assume it,
# unless it already names that principal. Existing statements are kept (one with the same Sid is replaced).
ensure_trust() {
  local role="$1" principal="$2" sid="$3" current
  current=$(query iam get-role --role-name "$role" --query Role.AssumeRolePolicyDocument --output json) || die "get-role $role failed"
  [ "$DRY_RUN" = 1 ] || [ -n "$current" ] || die "get-role $role returned no trust policy"
  if [ "$DRY_RUN" = 1 ]; then
    printf '    + %s\n' "$(fmt_admin iam update-assume-role-policy --role-name "$role" --policy-document "file://$WORK/trust-$role.json")   (only if $principal is not trusted yet)"
    return 0
  fi
  if printf '%s' "$current" | grep -q "\"$principal\""; then
    note "trust policy of $role already allows $principal"
    return 0
  fi
  command -v python3 >/dev/null 2>&1 || die "python3 is needed to merge $principal into the existing trust policy of $role. Add this statement by hand and rerun: {\"Sid\":\"$sid\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"$principal\"},\"Action\":\"sts:AssumeRole\"}"
  printf '%s' "$current" | python3 -c '
import json, sys
doc = json.load(sys.stdin)
principal, sid = sys.argv[1], sys.argv[2]
st = doc.get("Statement", [])
if isinstance(st, dict): st = [st]
st = [s for s in st if s.get("Sid") != sid]
st.append({"Sid": sid, "Effect": "Allow", "Principal": {"AWS": principal}, "Action": "sts:AssumeRole"})
doc["Statement"] = st
json.dump(doc, sys.stdout, indent=2)
' "$principal" "$sid" > "$WORK/trust-$role.json"
  run_when_principal_resolves iam update-assume-role-policy --role-name "$role" --policy-document "file://$WORK/trust-$role.json"
  note "added $principal to the trust policy of $role (existing principals kept)"
}

# ---- the advisor's API ----------------------------------------------------------------------------------------------
advisor_reachable() { curl -fsS -m 10 "$ADVISOR_URL/health" >/dev/null 2>&1; }
# advisor_call METHOD PATH BODY: prints the response body; fails (printing the body) on an HTTP error.
advisor_call() {
  local method="$1" path="$2" body="$3" out code
  local -a hdr=()
  if [ -n "$API_TOKEN" ]; then hdr=(-H "x-api-token: $API_TOKEN" -H "authorization: Bearer $API_TOKEN"); fi
  out=$(curl -sS -m 180 -X "$method" "$ADVISOR_URL$path" -H 'content-type: application/json' ${hdr[@]+"${hdr[@]}"} --data "$body" -w '\n%{http_code}') || { printf '%s' "$out"; return 1; }
  code=${out##*$'\n'}
  out=${out%$'\n'*}
  printf '%s' "$out"
  case "$code" in 2*) return 0 ;; esac
  return 1
}
# The PUT /api/settings/aws answer: what Steampipe and the SDK said. Fails when the test failed.
summarize_settings() {
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$1" <<'PY'
import json, sys
r = json.loads(sys.argv[1])
t, s = r.get("test") or {}, r.get("sdk") or {}
print("    Steampipe: " + ("connected to account %s" % t.get("accountId") if t.get("ok") else "FAILED: %s" % t.get("error")))
print("    SDK:       " + (("%s" % s.get("arn")) if s.get("ok") else "FAILED: %s" % s.get("error")))
sys.exit(0 if t.get("ok") and s.get("ok", True) else 1)
PY
  else
    printf '    %s\n' "$1"
    case "$1" in *'"test":{"ok":true'*) return 0 ;; esac
    return 1
  fi
}
# The POST /api/permissions/check answer: counts per status and the missing actions. Fails when anything is missing.
summarize_check() {
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$1" <<'PY'
import json, sys
r = json.loads(sys.argv[1])
res = r.get("results") or []
counts = {}
for x in res: counts[x.get("status")] = counts.get(x.get("status"), 0) + 1
print("    account %s, region %s: %d ok, %d missing, %d error, %d skipped (%s ms)" % (r.get("account_id"), r.get("region"), counts.get("ok", 0), counts.get("missing", 0), counts.get("error", 0), counts.get("skipped", 0), r.get("took_ms")))
if r.get("credentials_error"): print("    credentials: %s" % r["credentials_error"])
for x in res:
    if x.get("status") in ("missing", "error"): print("    %s %s: %s" % (x["status"], x.get("label"), (x.get("message") or "")[:200]))
if r.get("missing"): print("    missing actions: %s" % ", ".join(r["missing"]))
sys.exit(1 if r.get("missing") or r.get("credentials_error") else 0)
PY
  else
    printf '    %s\n' "$1"
    case "$1" in *'"missing":[]'*) return 0 ;; esac
    return 1
  fi
}

# ---- steps ----------------------------------------------------------------------------------------------------------
step 'Detect the AWS account and the admin identity'
for tool in aws curl; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    if [ "$DRY_RUN" = 1 ]; then warn "$tool is not installed (a dry run does not need it; the real run does)"; else die "$tool is not installed$([ "$tool" = aws ] && printf ' (https://aws.amazon.com/cli/)')"; fi
  fi
done
if [ "$DRY_RUN" = 1 ]; then
  ACCOUNT_ID="123456789012"
  CALLER_ARN="arn:aws:iam::123456789012:user/<you>"
  note "dry run: no AWS call is made, every check is assumed to find nothing, the account id is a placeholder"
else
  identity=$(aws_admin sts get-caller-identity --output text --query '[Account,Arn]' 2>"$WORK/err") || die "aws sts get-caller-identity failed (are admin credentials configured in this terminal?): $(cat "$WORK/err")"
  read -r ACCOUNT_ID CALLER_ARN <<< "$identity"
  case "$ACCOUNT_ID" in [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]) ;; *) die "unexpected account id: $ACCOUNT_ID" ;; esac
fi
ROLE_ARN="arn:aws:iam::$ACCOUNT_ID:role/$ROLE_NAME"
if [ "$PATH_KIND" = member-role ] && [ "$DRY_RUN" != 1 ]; then
  parent_account="${PRINCIPAL_ARN#arn:aws:iam::}"; parent_account="${parent_account%%:*}"
  [ "$ACCOUNT_ID" != "$parent_account" ] || die "this terminal is an admin of $ACCOUNT_ID, which is the PARENT (the account behind $PRINCIPAL_ARN). The member script must run with the CHILD account's admin credentials: sign in to the child (aws sso login --profile <child admin profile>) and rerun with --profile <child admin profile>, or AWS_PROFILE set to it. Nothing was changed."
fi
write_documents
note "account $ACCOUNT_ID, running as $CALLER_ARN"

step 'Create the read-only role aws-advisor-read trusted by parent'\''s identity arn:aws:iam::888722792401:role/aws-advisor-read'
if exists iam get-role --role-name "$ROLE_NAME"; then
  note "role $ROLE_NAME exists"
  ensure_trust "$ROLE_NAME" "$PRINCIPAL_ARN" "$PRINCIPAL_SID"
else
  run_when_principal_resolves iam create-role --role-name "$ROLE_NAME" --assume-role-policy-document "file://$WORK/trust.json" --description "aws-advisor read-only" --tags Key=app,Value=aws-advisor
  note "created $ROLE_ARN trusting $PRINCIPAL_ARN"
fi

step 'Put the read-only policy on aws-advisor-read'
run iam put-role-policy --role-name "$ROLE_NAME" --policy-name "$ROLE_NAME" --policy-document "file://$WORK/policy.json"
note "inline policy $ROLE_NAME on $ROLE_ARN is the recommended read-only policy (ssm:SendCommand only on document $PROBE_DOCUMENT)"

step 'Create the read-only SSM probe documents (AwsAdvisorProbe-host, AwsAdvisorProbe-docker, AwsAdvisorProbe-apps, AwsAdvisorProbe-software) in us-east-1'
for kind in host docker apps software; do
  name="$PROBE_DOCUMENT-$kind"; file="$WORK/probe-$kind.json"
  DOC_ARN="arn:aws:ssm:$REGION:$ACCOUNT_ID:document/$name"
  if exists ssm describe-document --name "$name" --region "$REGION"; then
    current=$(query ssm get-document --name "$name" --document-format JSON --region "$REGION" --query Content --output text) || die "get-document $name failed"
    if [ "$(printf '%s' "$current" | squeeze)" = "$(squeeze < "$file")" ]; then
      note "up to date ($PROBE_VERSION $kind): $DOC_ARN"
    elif aws_admin ssm update-document --name "$name" --content "file://$file" --document-version '$LATEST' --document-format JSON --region "$REGION" >/dev/null 2>"$WORK/err"; then
      latest=$(aws_admin ssm describe-document --name "$name" --region "$REGION" --query Document.LatestVersion --output text)
      aws_admin ssm update-document-default-version --name "$name" --document-version "$latest" --region "$REGION" >/dev/null
      note "updated to version $latest ($PROBE_VERSION $kind): $DOC_ARN"
    elif grep -q DuplicateDocumentContent "$WORK/err"; then
      note "already up to date ($PROBE_VERSION $kind): $DOC_ARN"
    else
      die "update-document $name failed: $(cat "$WORK/err")"
    fi
  else
    run ssm create-document --name "$name" --document-type Command --document-format JSON --content "file://$file" --region "$REGION" --tags Key=app,Value=aws-advisor
    note "created $DOC_ARN ($PROBE_VERSION $kind)"
  fi
done

step 'Register this account with the advisor (http://localhost:9034) as a member and test the role from the parent'
NAME_JSON=$(printf '%s' "${MEMBER_NAME:-$ACCOUNT_ID}" | sed 's/"/\"/g')
BODY='{"account_id":"'"$ACCOUNT_ID"'","name":"'"$NAME_JSON"'","role_arn":"'"$ROLE_ARN"'"}'
note "member: account $ACCOUNT_ID, read role $ROLE_ARN, trusting $PRINCIPAL_ARN"
if [ "$DRY_RUN" = 1 ]; then
  printf '    + %s\n' "curl -fsS -X POST '$ADVISOR_URL/api/accounts' -H 'content-type: application/json' $TOKEN_HINT-d '$BODY'"
else
  advisor_reachable || die "the advisor at $ADVISOR_URL does not answer. Start it, or add the member by hand under Settings › Member accounts: account $ACCOUNT_ID, read role $ROLE_ARN."
  resp=$(advisor_call POST /api/accounts "$BODY") || die "POST $ADVISOR_URL/api/accounts failed: $resp"
  if command -v python3 >/dev/null 2>&1; then
    printf '%s' "$resp" | python3 -c '
import json, sys
r = json.load(sys.stdin); t = r.get("test") or {}
print("    saved as member", (r.get("saved") or {}).get("account_id", "?"), "|", "role assumed from the parent: ok" if t.get("ok") else "role test failed: " + str(t.get("error") or t))
sys.exit(0 if t.get("ok") else 2)' || warn "the member is saved but the parent could not assume its role yet: check the trust policy (the parent identity above) and the parent policy statement AdvisorAssumeMembers, then Settings › Member accounts › Test"
  else
    note "$resp"
  fi
  ADVISOR_OK=1
fi

printf '\n'
if [ "$DRY_RUN" = 1 ]; then
  printf '%s\n' "Dry run complete: nothing was changed. Run the script without --dry-run (or fetch it without dryRun=1) to apply."
else
  printf '%s\n' "Done. Account $ACCOUNT_ID is a member: its read role $ROLE_ARN trusts $PRINCIPAL_ARN, and the advisor at $ADVISOR_URL lists it under Member accounts. A role created seconds ago can fail its first test (IAM propagation); Settings > Member accounts > Test repeats it."
  printf '%s\n' "The next collection run reads this account with its own account id on every row. An actuator role (the executor acting here) is a separate, manual step: the actuator policy on the Auto-actions page, trusting the same parent identity."
fi
