/** Registers every action module with the executor; imported once at startup (src/index.ts). */
import { registerAction } from "../executor.js";
import { acuWindowAction } from "./acu_window.js";
import { snapshotArchiveAction } from "./snapshot_archive.js";
import { ebsIopsTrimAction } from "./ebs_iops_trim.js";
import { logRetentionAction } from "./log_retention.js";
import { s3RequestMetricsAction } from "./s3_request_metrics.js";
import { auroraStorageAction } from "./aurora_storage.js";
import { s3LifecycleAction } from "./s3_lifecycle.js";
import { ebsGp3MigrateAction } from "./ebs_gp3_migrate.js";
import { ecrLifecycleAction } from "./ecr_lifecycle.js";
import { swarmParkAction } from "./swarm_park.js";
import { eipReleaseAction } from "./eip_release.js";
import { vpcGatewayEndpointAction } from "./vpc_gateway_endpoint.js";
import { kmsKeyRetireAction } from "./kms_key_retire.js";
import { dynamodbCapacityModeAction } from "./dynamodb_capacity_mode.js";
import { snapshotDeleteAction } from "./snapshot_delete.js";
import { idleLoadBalancerAction } from "./idle_load_balancer.js";
import { scheduleHoursAction } from "./schedule_hours.js";
import { ebsThroughputTrimAction } from "./ebs_throughput_trim.js";
import { cpuCreditSpecAction } from "./cpu_credit_spec.js";
import { efsLifecycleAction } from "./efs_lifecycle.js";
import { alarmCleanupAction } from "./alarm_cleanup.js";
import { logRetentionTuneAction } from "./log_retention_tune.js";
import { s3MultipartAbortAction } from "./s3_multipart_abort.js";
import { lambdaMemoryAction } from "./lambda_memory.js";
import { beanstalkScaleAction } from "./beanstalk_scale.js";
import { usageScheduleAction } from "./usage_schedule.js";
import { consentTagAction } from "./consent_tag.js";

registerAction(acuWindowAction);
registerAction(snapshotArchiveAction);
registerAction(ebsIopsTrimAction);
registerAction(logRetentionAction);
registerAction(s3RequestMetricsAction);
registerAction(auroraStorageAction);
registerAction(s3LifecycleAction);
registerAction(ebsGp3MigrateAction);
registerAction(ecrLifecycleAction);
registerAction(swarmParkAction);
registerAction(eipReleaseAction);
registerAction(vpcGatewayEndpointAction);
registerAction(kmsKeyRetireAction);
registerAction(dynamodbCapacityModeAction);
registerAction(snapshotDeleteAction);
registerAction(idleLoadBalancerAction);
registerAction(scheduleHoursAction);
registerAction(ebsThroughputTrimAction);
registerAction(cpuCreditSpecAction);
registerAction(efsLifecycleAction);
registerAction(alarmCleanupAction);
registerAction(logRetentionTuneAction);
registerAction(s3MultipartAbortAction);
registerAction(lambdaMemoryAction);
registerAction(beanstalkScaleAction);
registerAction(usageScheduleAction);
registerAction(consentTagAction);
