/** Registers every AWS action module with the executor, under the AWS provider; loaded by the AWS adapter (src/adapters/aws/index.ts actions.register). */
import { registerAction } from "../executor.js";
import { AWS } from "../adapters/types.js";
import { acuWindowAction } from "./acu_window.js";
import { snapshotArchiveAction } from "./snapshot_archive.js";
import { ebsIopsTrimAction } from "./ebs_iops_trim.js";
import { logRetentionAction } from "./log_retention.js";
import { s3RequestMetricsAction } from "./s3_request_metrics.js";
import { auroraStorageAction } from "./aurora_storage.js";
import { s3LifecycleAction } from "./s3_lifecycle.js";
import { ebsGp3MigrateAction } from "./ebs_gp3_migrate.js";
import { ecrLifecycleAction } from "./ecr_lifecycle.js";
import { swarmParkAction } from "./swarm_park.js";
import { eipReleaseAction } from "./eip_release.js";
import { vpcGatewayEndpointAction } from "./vpc_gateway_endpoint.js";
import { kmsKeyRetireAction } from "./kms_key_retire.js";
import { dynamodbCapacityModeAction } from "./dynamodb_capacity_mode.js";
import { snapshotDeleteAction } from "./snapshot_delete.js";
import { idleLoadBalancerAction } from "./idle_load_balancer.js";
import { scheduleHoursAction } from "./schedule_hours.js";
import { ebsThroughputTrimAction } from "./ebs_throughput_trim.js";
import { cpuCreditSpecAction } from "./cpu_credit_spec.js";
import { efsLifecycleAction } from "./efs_lifecycle.js";
import { alarmCleanupAction } from "./alarm_cleanup.js";
import { logRetentionTuneAction } from "./log_retention_tune.js";
import { s3MultipartAbortAction } from "./s3_multipart_abort.js";
import { lambdaMemoryAction } from "./lambda_memory.js";
import { beanstalkScaleAction } from "./beanstalk_scale.js";
import { beanstalkPressureAction } from "./beanstalk_pressure.js";
import { usageScheduleAction } from "./usage_schedule.js";
import { consentTagAction } from "./consent_tag.js";
import { ec2HibernateMigrateAction } from "./ec2_hibernate_migrate.js";
import { readPolicyAction } from "./read_policy.js";

registerAction(acuWindowAction, AWS);
registerAction(snapshotArchiveAction, AWS);
registerAction(ebsIopsTrimAction, AWS);
registerAction(logRetentionAction, AWS);
registerAction(s3RequestMetricsAction, AWS);
registerAction(auroraStorageAction, AWS);
registerAction(s3LifecycleAction, AWS);
registerAction(ebsGp3MigrateAction, AWS);
registerAction(ecrLifecycleAction, AWS);
registerAction(swarmParkAction, AWS);
registerAction(eipReleaseAction, AWS);
registerAction(vpcGatewayEndpointAction, AWS);
registerAction(kmsKeyRetireAction, AWS);
registerAction(dynamodbCapacityModeAction, AWS);
registerAction(snapshotDeleteAction, AWS);
registerAction(idleLoadBalancerAction, AWS);
registerAction(scheduleHoursAction, AWS);
registerAction(ebsThroughputTrimAction, AWS);
registerAction(cpuCreditSpecAction, AWS);
registerAction(efsLifecycleAction, AWS);
registerAction(alarmCleanupAction, AWS);
registerAction(logRetentionTuneAction, AWS);
registerAction(s3MultipartAbortAction, AWS);
registerAction(lambdaMemoryAction, AWS);
registerAction(beanstalkScaleAction, AWS);
registerAction(beanstalkPressureAction, AWS);
registerAction(usageScheduleAction, AWS);
registerAction(consentTagAction, AWS);
registerAction(ec2HibernateMigrateAction, AWS);
registerAction(readPolicyAction, AWS);
