import { db } from "./db.js";
import { adapters } from "./adapters/index.js";

/**
 * Playbooks: what a finding means and how to act on it. Every playbook is generated by the agent from official
 * sources (the benchmark mod's control text and the provider pages listed in CONTROL_SOURCES below), judged by
 * Jev for tier and effort, stored in the playbooks table and mirrored to the graph with its citations. Nothing is
 * hand-written: a control with no generated playbook has none until the generator writes it. The resolution flow
 * in src/resolve.ts tailors the playbook in force to one resource with the graph, Jev and the agent.
 */

export type PlaybookTier = "auto" | "approve" | "report";
export type PlaybookEffort = "low" | "medium" | "high";

// The generated playbooks (src/playbook_gen.ts writes them).
db.exec(`create table if not exists playbooks (
  control_id text primary key, title text, meaning text, act_when text, ignore_when text, steps text not null default '[]', saving text, references_ text not null default '[]', gaps text not null default '[]',
  confidence real, tier text, effort text, judged text, sources text not null default '[]', generated_at text, generated_by text, stale_after text, review_status text, published integer not null default 0, reason text,
  job_id integer, status text not null default 'completed'
)`);

/** Where a playbook came from: the generated row's record. */
export interface PlaybookProvenance {
  origin: "generated";
  generated_at?: string | null; generated_by?: string | null; stale_after?: string | null;
  review_status?: string | null; published?: boolean; reason?: string | null; confidence?: number | null;
  sources?: { id: string; hash: string; title: string | null; origin: string }[]; gaps?: string[];
  judged?: { tier: string; effort: string; irreversible: number | null; service_impact: number | null; covers: number | null; judged: boolean } | null;
  /** a generated playbook that is not published: why it is held (nothing is in force meanwhile) */
  held?: { review_status: string; reason: string | null; generated_at: string | null } | null;
}

export interface Playbook {
  control_id: string;
  title: string;
  /** What the alarm actually says, in one or two sentences. */
  meaning: string;
  /** When it is worth acting on. */
  act_when: string;
  /** When to leave it alone (and why). */
  ignore_when: string;
  /** Concrete steps, in order. */
  steps: string[];
  /** The saving formula, in words. */
  saving: string;
  /** auto = reversible and safe to automate; approve = needs a human; report = never automate. */
  tier: PlaybookTier;
  effort: PlaybookEffort;
  references?: string[];
  /** per step, the source id the step cites */
  citations?: (string | null)[];
  provenance?: PlaybookProvenance;
}



/**
 * The official sources each control is documented by: the pages the generator reads and cites, next to the
 * benchmark mod's own control text. Nothing here is a playbook: every playbook is written by the agent from these
 * sources (src/playbook_gen.ts), stored in the playbooks table and mirrored to the graph with its citations; a control
 * without a generated playbook shows none. A Thrifty control's primary source is the benchmark mod's own text (and the
 * pages that text references); an empty list here means the mod is enough. Add a URL to give the agent a better
 * source; never prose. The Vercel controls list theirs in src/adapters/vercel/rules.ts.
 */
export const CONTROL_SOURCES: Record<string, string[]> = {
  "aws_thrifty.control.apigateway_stage_with_caching_disabled": [],
  "aws_thrifty.control.buckets_with_no_lifecycle": ["https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html"],
  "aws_thrifty.control.cw_log_group_retention": [],
  "aws_thrifty.control.cw_log_stream_unused": [],
  "aws_thrifty.control.dynamodb_table_without_autoscaling": [],
  "aws_thrifty.control.ebs_snapshot_max_age": [],
  "aws_thrifty.control.ebs_unused_snapshots": [],
  "aws_thrifty.control.ebs_volumes_on_stopped_instances": [],
  "aws_thrifty.control.ebs_with_low_usage": [],
  "aws_thrifty.control.ec2_instance_older_generation": [],
  "aws_thrifty.control.ec2_instance_with_graviton": ["https://aws.amazon.com/ec2/graviton/", "https://github.com/aws/aws-graviton-getting-started"],
  "aws_thrifty.control.ec2_reserved_instance_lease_expiration_days": [],
  "aws_thrifty.control.ecr_repository_unused_images": ["https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html"],
  "aws_thrifty.control.ecs_cluster_low_utilization": [],
  "aws_thrifty.control.elasticache_cluster_long_running": [],
  "aws_thrifty.control.full_month_cost_changes": [],
  "aws_thrifty.control.instances_with_low_utilization": [],
  "aws_thrifty.control.lambda_function_excessive_timeout": [],
  "aws_thrifty.control.lambda_function_with_graviton": ["https://docs.aws.amazon.com/lambda/latest/dg/foundation-arch.html"],
  "aws_thrifty.control.large_ebs_volumes": [],
  "aws_thrifty.control.long_running_ec2_instances": [],
  "aws_thrifty.control.long_running_rds_db_instances": [],
  "aws_thrifty.control.rds_db_instance_with_graviton": ["https://aws.amazon.com/rds/instance-types/"],
  "aws_thrifty.control.rds_db_low_utilization": [],
  "aws_thrifty.control.route53_record_higher_ttl": [],
  "aws_thrifty.control.secretsmanager_secret_unused": [],
  "aws_thrifty.control.stale_dynamodb_table_data": [],
  "aws_thrifty.control.unattached_eips": [],
  "query.commitments": ["https://docs.aws.amazon.com/savingsplans/latest/userguide/what-is-savings-plans.html", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-reserved-instances.html"],
  "query.eip_unattached": ["https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html", "https://aws.amazon.com/vpc/pricing/"],
  "query.idle_instances": ["https://docs.aws.amazon.com/cost-management/latest/userguide/ce-rightsizing.html", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html"],
  "query.log_groups_no_retention": ["https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html", "https://aws.amazon.com/cloudwatch/pricing/"],
  "query.old_snapshots": ["https://docs.aws.amazon.com/ebs/latest/userguide/ebs-deleting-snapshot.html", "https://docs.aws.amazon.com/ebs/latest/userguide/snapshot-lifecycle.html"],
  "query.stopped_instance_ebs": ["https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Stop_Start.html", "https://aws.amazon.com/ebs/pricing/"],
  "rule.aurora_storage_tier": ["https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.StorageReliability.html", "https://aws.amazon.com/rds/aurora/pricing/"],
  "rule.enable_flow_logs": ["https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html", "https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-s3.html"],
  // who can get in (src/identity_rules.ts)
  "rule.identity_central_root_access": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-enable-root-access.html", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html", "https://docs.aws.amazon.com/IAM/latest/UserGuide/root-user-best-practices.html"],
  "rule.identity_center_mfa": ["https://docs.aws.amazon.com/singlesignon/latest/userguide/mfa-configure.html", "https://docs.aws.amazon.com/singlesignon/latest/userguide/mfa-types.html", "https://docs.aws.amazon.com/singlesignon/latest/userguide/how-to-configure-mfa-device-enforcement.html"],
  "rule.identity_key_on_laptop": ["https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html", "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html"],
  "rule.identity_mfa_device_removed": ["https://docs.aws.amazon.com/singlesignon/latest/userguide/how-to-register-device.html", "https://docs.aws.amazon.com/singlesignon/latest/userguide/mfa-configure.html"],
  "rule.identity_role_wide_trust": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html", "https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services", "https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html", "https://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html"],
  "rule.identity_unused_write": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_last-accessed.html", "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#grant-least-privilege", "https://docs.aws.amazon.com/singlesignon/latest/userguide/permissionsetsconcept.html"],
  "rule.identity_escalation": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_passrole.html", "https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_understand-policy-summary-access-level-summaries.html"],
  "rule.identity_indirect_admin": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_terms-and-concepts.html", "https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-restrict-access.html", "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html"],
  "rule.identity_unused_outside_role": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_last-accessed.html", "https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-findings.html"],
};

/** The playbook for a control id (Thrifty control, `query.*` control or `rule.*` id), or null. */
/** A generated row as the Playbook the pages read, with its provenance. */
export function generatedPlaybook(controlId: string): (Playbook & { provenance: PlaybookProvenance }) | null {
  let r: any; try { r = db.prepare("select * from playbooks where control_id = ? and status = 'completed'").get(controlId); } catch { r = null; }
  if (!r) return null;
  const j = (() => { try { return JSON.parse(r.judged || "null"); } catch { return null; } })();
  const steps: { text: string; source: string | null }[] = (() => { try { return JSON.parse(r.steps || "[]"); } catch { return []; } })();
  return {
    control_id: r.control_id, title: r.title, meaning: r.meaning, act_when: r.act_when, ignore_when: r.ignore_when, steps: steps.map((x) => x.text), citations: steps.map((x) => x.source ?? null), saving: r.saving ?? "unknown",
    tier: (r.tier as PlaybookTier) ?? "approve", effort: (r.effort as PlaybookEffort) ?? "medium", references: JSON.parse(r.references_ || "[]"),
    provenance: { origin: "generated", generated_at: r.generated_at, generated_by: r.generated_by, stale_after: r.stale_after, review_status: r.review_status, published: Boolean(r.published), reason: r.reason, confidence: r.confidence, sources: JSON.parse(r.sources || "[]"), gaps: JSON.parse(r.gaps || "[]"), judged: j },
  };
}

/** The playbook in force for a control: the published generated one; nothing when it is unwritten or held. */
export function playbookFor(controlId: string | null | undefined): Playbook | null {
  if (!controlId) return null;
  if (/^vercel_/.test(controlId)) controlId = controlId.replace(/^vercel_/, "vercel.control.");
  const g = generatedPlaybook(controlId);
  return g?.provenance.published ? g : null;
}

/** A generated playbook that exists but is not in force, with why: the pages say so instead of showing nothing silently. */
export function heldPlaybook(controlId: string): { review_status: string; reason: string | null; generated_at: string | null } | null {
  const g = generatedPlaybook(controlId);
  return g && !g.provenance.published ? { review_status: g.provenance.review_status ?? "held", reason: g.provenance.reason ?? null, generated_at: g.provenance.generated_at ?? null } : null;
}

/** Every control with a playbook in force: the published generated ones. */
export function listPlaybooks(): Playbook[] {
  let gen: string[] = []; try { gen = (db.prepare("select control_id from playbooks where status = 'completed' and published = 1").all() as { control_id: string }[]).map((r) => r.control_id); } catch { gen = []; }
  return gen.map((id) => playbookFor(id)).filter((p): p is Playbook => Boolean(p));
}

/** Whether the advisor knows a control at all: it has sources listed, or a playbook was generated for it. */
export function knownControl(controlId: string): boolean { return Boolean(CONTROL_SOURCES[controlId]) || Boolean(generatedPlaybook(controlId)); }

export interface PlaybookSummary { control_id: string; title: string; tier: PlaybookTier; effort: PlaybookEffort }

/** What the findings list carries per control: enough for a badge, not the whole text. */
export const playbookSummary = (p: Playbook): PlaybookSummary => ({ control_id: p.control_id, title: p.title, tier: p.tier, effort: p.effort });

/** The playbook's steps as one sentence, for the end of a recommendation's rationale: the gist of each step. */
export function stepsSentence(p: Playbook): string {
  const MAX = 70;
  const clause = (step: string) => {
    // Backticked commands may contain ". " or ": "; hide them while cutting the clause.
    const codes: string[] = [];
    let s = step.replace(/`[^`]*`/g, (m) => { codes.push(m); return `\u0000${codes.length - 1}\u0000`; });
    // "Kubernetes: instead of ..." is a label plus the clause; "List what runs on the box: ssh in ..." is a clause plus detail.
    const label = /^([^.;:]{1,28}):\s+/.exec(s);
    if (label && label[1].length >= 14) s = label[1];
    else {
      if (label) s = s.slice(label[0].length);
      s = s.split(/[.;:](?=\s|$)/)[0];
      if (s.length > MAX) { const cut = s.lastIndexOf(",", MAX); s = cut > 20 ? s.slice(0, cut) : s.slice(0, s.lastIndexOf(" ", MAX)) + "…"; }
      if (label) s = `${label[1].toLowerCase()}: ${s}`;
    }
    s = s.trim().replace(/\u0000(\d+)\u0000/g, (_, i) => codes[Number(i)]);
    return s.replace(/^[A-Z](?=[a-z])/, (c) => c.toLowerCase());
  };
  return `Playbook (${p.title}): ${p.steps.map(clause).join(", then ")}.`;
}

/** The control a rules-based recommendation comes from, when the rule has one obvious origin. */
export const RULE_CONTROL: Record<string, string> = {
  stopped_instance_ebs: "query.stopped_instance_ebs",
  old_snapshot: "query.old_snapshots",
  eip_unattached: "query.eip_unattached",
  log_group_no_retention: "query.log_groups_no_retention",
  idle_instance: "query.idle_instances",
  aurora_storage_tier: "rule.aurora_storage_tier",
  enable_flow_logs: "rule.enable_flow_logs",
  identity_central_root_access: "rule.identity_central_root_access",
  identity_center_mfa: "rule.identity_center_mfa",
  identity_key_on_laptop: "rule.identity_key_on_laptop",
  identity_mfa_device_removed: "rule.identity_mfa_device_removed",
  identity_role_wide_trust: "rule.identity_role_wide_trust",
  identity_unused_outside_role: "rule.identity_unused_outside_role",
  identity_unused_write: "rule.identity_unused_write",
  identity_escalation: "rule.identity_escalation",
  identity_indirect_admin: "rule.identity_indirect_admin",
  review_s3_lifecycle: "aws_thrifty.control.buckets_with_no_lifecycle",
};

/** Origin control of a recommendation: the evidence's `playbook` (the graviton rule sets it), else the rule's control. */
export function controlForRecommendation(rec: { rule: string; evidence?: unknown }): string | null {
  // a provider whose rules name their control in the rule itself says so (vercel_x → vercel.control.x)
  for (const a of adapters()) { const c = a.rules?.controlForRule?.(rec.rule); if (c) return c; }
  const ev = typeof rec.evidence === "string" ? (() => { try { return JSON.parse(rec.evidence as string); } catch { return null; } })() : rec.evidence;
  const fromEvidence = ev && typeof ev === "object" && typeof (ev as any).playbook === "string" ? (ev as any).playbook : null;
  if (fromEvidence && knownControl(fromEvidence)) return fromEvidence;
  return RULE_CONTROL[rec.rule] ?? null;
}
